server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: palmetto-app
      auto-offset-reset: earliest

palmetto-app:
  producer:
    topic-name: notification_topic
  consumer:
    topic-name: order_topic